```{r libraries}
library(dplyr)
library(ggplot2)
library(latex2exp)

```

```{r dataset load}
# import
half_n = read.csv("dataset/half_n.csv")
square_n = read.csv("dataset/square_n.csv")
random_k = read.csv("dataset/random_k.csv")
quickselect_worst = read.csv("dataset/quickselect_worst.csv")
hundred_n = read.csv("dataset/hundred_n.csv")
static_size = read.csv("dataset/static_size.csv")

```

```{r statistics}
# generating stats for each analysis:

half_n_stats = half_n %>%
  group_by(size) %>%
  summarise( quickselect_average = mean(quickselect), 
             quickselect_variance = var(quickselect) ,
             heapselect_average = mean(heapselect), 
             heapselect_variance = var(heapselect),
             medianmediansselect_average = mean(medianmediansselect), 
             medianmediansselect_variance = var(medianmediansselect))

square_n_stats = square_n %>%
  group_by(size) %>%
  summarise( quickselect_average = mean(quickselect), 
             quickselect_variance = var(quickselect) ,
             heapselect_average = mean(heapselect), 
             heapselect_variance = var(heapselect),
             medianmediansselect_average = mean(medianmediansselect), 
             medianmediansselect_variance = var(medianmediansselect))

random_k_stats = random_k %>%
  group_by(size) %>%
  summarise( quickselect_average = mean(quickselect), 
             quickselect_variance = var(quickselect) ,
             heapselect_average = mean(heapselect), 
             heapselect_variance = var(heapselect),
             medianmediansselect_average = mean(medianmediansselect), 
             medianmediansselect_variance = var(medianmediansselect))

hundred_n_stats = hundred_n %>%
  group_by(size) %>%
  summarise( quickselect_average = mean(quickselect), 
             quickselect_variance = var(quickselect) ,
             heapselect_average = mean(heapselect), 
             heapselect_variance = var(heapselect),
             medianmediansselect_average = mean(medianmediansselect), 
             medianmediansselect_variance = var(medianmediansselect))

quickselect_worst_stats = quickselect_worst %>%
  group_by(size) %>%
  summarise( quickselect_average = mean(quickselect), 
             quickselect_variance = var(quickselect))

static_size_stats = static_size %>%
  group_by(k) %>%
  summarise( quickselect_average = mean(quickselect), 
             quickselect_variance = var(quickselect) ,
             minheapselect_average = mean(minheapselect), 
             minheapselect_variance = var(minheapselect),
             maxheapselect_average = mean(maxheapselect), 
             maxheapselect_variance = var(maxheapselect),
             medianmediansselect_average = mean(medianmediansselect), 
             medianmediansselect_variance = var(medianmediansselect))
```

```{r color palette}
# palette:
quickselect_color = "#a05195"
heapSelect_color = "#ff7c43"
medianMediansSelect_color = "#003f5c"

```

```{r linear scale graphs}
# LINEAR SCALE GRAPHS:
# k random:
random_k_stats  %>% ggplot( aes(x = size) ) + 
  geom_ribbon(aes(ymin = heapselect_average-heapselect_variance/2, 
                  ymax = heapselect_average+heapselect_variance/2), fill = "grey70") +
  geom_line(aes(y=heapselect_average,colour="heapSelect"),size=2 )+
  geom_ribbon(aes(ymin = quickselect_average-quickselect_variance/2, 
                  ymax = quickselect_average+quickselect_variance/2), fill = "grey70") +
  geom_line(aes(y=quickselect_average,colour="quickSelect"),size=2 )+
  geom_ribbon(aes(ymin = medianmediansselect_average-medianmediansselect_variance/2, 
                  ymax = medianmediansselect_average+medianmediansselect_variance/2), fill = "grey70") +
  geom_line(aes(y=medianmediansselect_average,colour="medianMediansSelect"),size=2 )+
  labs(x = "dimensione", y = "tempo (secondi)")+
  scale_color_manual(name = "Algoritmi di selezione", 
                     values = c("quickSelect" = quickselect_color, "heapSelect" = heapSelect_color, "medianMediansSelect" = medianMediansSelect_color))+
  scale_x_continuous(breaks = c(100, 1000000, 2000000, 3000000, 4000000, 5000000), labels = c("100", "1M", "2M", "3M", "4M", "5M")) +
  theme_light() + 
  theme(text=element_text(size = 20, family = "Times"))+ jpeg(width = 1000, height = 563, filename="graphs/random_k_linear.png", quality = 100)

# square n:
square_n_stats  %>% ggplot( aes(x = size) ) + 
  geom_ribbon(aes(ymin = heapselect_average-heapselect_variance/2, 
                  ymax = heapselect_average+heapselect_variance/2), fill = "grey70") +
  geom_line(aes(y=heapselect_average,colour="heapSelect"),size=2 )+
  geom_ribbon(aes(ymin = quickselect_average-quickselect_variance/2, 
                  ymax = quickselect_average+quickselect_variance/2), fill = "grey70") +
  geom_line(aes(y=quickselect_average,colour="quickSelect"),size=2 )+
  geom_ribbon(aes(ymin = medianmediansselect_average-medianmediansselect_variance/2, 
                  ymax = medianmediansselect_average+medianmediansselect_variance/2), fill = "grey70") +
  geom_line(aes(y=medianmediansselect_average,colour="medianMediansSelect"),size=2 )+
  labs(x = "dimensione", y = "tempo (secondi)") +
  scale_color_manual(name = "Algoritmi di selezione", values = c("quickSelect" = quickselect_color, "heapSelect" = heapSelect_color, "medianMediansSelect" = medianMediansSelect_color))+
  scale_x_continuous(breaks = c(100, 1000000, 2000000, 3000000, 4000000, 5000000), labels = c("100", "1M", "2M", "3M", "4M", "5M")) +
  theme_light() + theme(text=element_text(size = 20, family = "Times"))+ jpeg(width = 1000, height = 563, filename="graphs/square_n_linear.png", quality = 100)

# half n:
half_n_stats %>% ggplot( aes(x = size) ) + 
  geom_ribbon(aes(ymin = heapselect_average-heapselect_variance/2, 
                  ymax = heapselect_average+heapselect_variance/2), fill = "grey70") +
  geom_line(aes(y=heapselect_average,colour="heapSelect"),size=2 )+
  geom_ribbon(aes(ymin = quickselect_average-quickselect_variance/2, 
                  ymax = quickselect_average+quickselect_variance/2), fill = "grey70") +
  geom_line(aes(y=quickselect_average,colour="quickSelect"),size=2 )+
  geom_ribbon(aes(ymin = medianmediansselect_average-medianmediansselect_variance/2, 
                  ymax = medianmediansselect_average+medianmediansselect_variance/2), fill = "grey70") +
  geom_line(aes(y=medianmediansselect_average,colour="medianMediansSelect"),size=2 )+
  labs(x = "dimensione", y = "tempo (secondi)") +
  scale_color_manual(name = "Algoritmi di selezione", values = c("quickSelect" = quickselect_color, "heapSelect" = heapSelect_color, "medianMediansSelect" = medianMediansSelect_color))+
  scale_x_continuous(breaks = c(100, 1000000, 2000000, 3000000, 4000000, 5000000), labels = c("100", "1M", "2M", "3M", "4M", "5M")) +
  theme_light() + theme(text=element_text(size = 20, family = "Times"))+ jpeg(width = 1000, height = 563, filename="graphs/half_n_linear.png", quality = 100)

# hundred n:
hundred_n_stats %>% ggplot( aes(x = size) ) + 
  geom_ribbon(aes(ymin = heapselect_average-heapselect_variance/2, 
                  ymax = heapselect_average+heapselect_variance/2), fill = "grey70") +
  geom_line(aes(y=heapselect_average,colour="heapSelect"),size=2 )+
  geom_ribbon(aes(ymin = quickselect_average-quickselect_variance/2, 
                  ymax = quickselect_average+quickselect_variance/2), fill = "grey70") +
  geom_line(aes(y=quickselect_average,colour="quickSelect"),size=2 )+
  geom_ribbon(aes(ymin = medianmediansselect_average-medianmediansselect_variance/2, 
                  ymax = medianmediansselect_average+medianmediansselect_variance/2), fill = "grey70") +
  geom_line(aes(y=medianmediansselect_average,colour="medianMediansSelect"),size=2 )+
  labs(x = "dimensione", y = "tempo (secondi)") +
  scale_color_manual(name = "Algoritmi di selezione", values = c("quickSelect" = quickselect_color, "heapSelect" = heapSelect_color, "medianMediansSelect" = medianMediansSelect_color))+
  scale_x_continuous(breaks = c(100, 1000000, 2000000, 3000000, 4000000, 5000000), labels = c("100", "1M", "2M", "3M", "4M", "5M")) +
  theme_light() + theme(text=element_text(size = 20, family = "Times"))+ jpeg(width = 1000, height = 563, filename="graphs/hundred_n_linear.png", quality = 100)

# quick select worst case:
quickselect_worst_stats %>% ggplot( aes(x = size) ) + 
  geom_ribbon(aes(ymin = quickselect_average-quickselect_variance/2, 
                  ymax = quickselect_average+quickselect_variance/2), fill = "grey70") +
  geom_line(aes(y=quickselect_average, colour="quickSelect"),size=2 )+
  stat_smooth(aes(y = quickselect_average), method = "lm", formula = y ~ x + I(x^2), size = 2, se=F, color="black", linetype="dotted") +
  labs(x = "dimensione", y = "tempo (secondi)") +
  scale_color_manual(name = "Algoritmi di selezione", values = c("quickSelect" = quickselect_color)) +
  theme_light() + theme(text=element_text(size = 20, family = "Times"))+ jpeg(width = 1000, height = 563, filename="graphs/quickselect_worst_linear.png", quality = 100)

```

```{r logaritmic scale graphs}
# LOG SCALE GRAPHS:
# k random:
random_k_stats  %>% ggplot( aes(x = size) ) + 
  geom_line(aes(y=quickselect_average,colour="quickSelect"),size=2 )+
  geom_line(aes(y=heapselect_average,colour="heapSelect"),size=2) +
  geom_line(aes(y=medianmediansselect_average,colour="medianMediansSelect"),size=2) +
  labs(x = "dimensione", y = "tempo (secondi)") +
  scale_color_manual(name = "Algoritmi di selezione", values = c("quickSelect" = quickselect_color, "heapSelect" = heapSelect_color, "medianMediansSelect" = medianMediansSelect_color)) +
  scale_x_continuous(breaks = c(100, 1000000, 2000000, 3000000, 4000000, 5000000), labels = c("100", "1M", "2M", "\n3M", "\n\n4M", "\n\n\n5M"), trans = 'log') +
  scale_y_continuous(trans='log', labels = scales::number_format(accuracy = 0.00001)) +
  theme_light() + theme(text=element_text(size = 20, family = "Times"))+ jpeg(width = 1000, height = 563, filename="graphs/random_k_log.png", quality = 100)

# square n:
square_n_stats  %>% ggplot( aes(x = size) ) + 
  geom_line(aes(y=quickselect_average,colour="quickSelect"),size=2 )+
  geom_line(aes(y=heapselect_average,colour="heapSelect"),size=2) +
  geom_line(aes(y=medianmediansselect_average,colour="medianMediansSelect"),size=2) +
  labs(x = "dimensione", y = "tempo (secondi)") +
  scale_color_manual(name = "Algoritmi di selezione", values = c("quickSelect" = quickselect_color, "heapSelect" = heapSelect_color, "medianMediansSelect" = medianMediansSelect_color)) +
  scale_x_continuous(breaks = c(100, 1000000, 2000000, 3000000, 4000000, 5000000), labels = c("100", "1M", "2M", "\n3M", "\n\n4M", "\n\n\n5M"), trans = 'log') +
  scale_y_continuous(trans='log', labels = scales::number_format(accuracy = 0.00001)) +
  theme_light() + theme(text=element_text(size = 20, family = "Times"))+ jpeg(width = 1000, height = 563, filename="graphs/square_n_log.png", quality = 100)

# half n:
half_n_stats  %>% ggplot( aes(x = size) ) + 
  geom_line(aes(y=quickselect_average,colour="quickSelect"),size=2 )+
  geom_line(aes(y=heapselect_average,colour="heapSelect"),size=2) +
  geom_line(aes(y=medianmediansselect_average,colour="medianMediansSelect"),size=2) +
  labs(x = "dimensione", y = "tempo (secondi)") +
  scale_color_manual(name = "Algoritmi di selezione", values = c("quickSelect" = quickselect_color, "heapSelect" = heapSelect_color, "medianMediansSelect" = medianMediansSelect_color)) +
  scale_x_continuous(breaks = c(100, 1000000, 2000000, 3000000, 4000000, 5000000), labels = c("100", "1M", "2M", "\n3M", "\n\n4M", "\n\n\n5M"), trans = 'log') +
  scale_y_continuous(trans='log', labels = scales::number_format(accuracy = 0.00001)) +
  theme_light() + theme(text=element_text(size = 20, family = "Times"))+ jpeg(width = 1000, height = 563, filename="graphs/half_n_log.png", quality = 100)

# hundred n:
hundred_n_stats  %>% ggplot( aes(x = size) ) + 
  geom_line(aes(y=quickselect_average,colour="quickSelect"),size=2 )+
  geom_line(aes(y=heapselect_average,colour="heapSelect"),size=2) +
  geom_line(aes(y=medianmediansselect_average,colour="medianMediansSelect"),size=2) +
  labs(x = "dimensione", y = "tempo (secondi)") +
  scale_color_manual(name = "Algoritmi di selezione", values = c("quickSelect" = quickselect_color, "heapSelect" = heapSelect_color, "medianMediansSelect" = medianMediansSelect_color)) +
  scale_x_continuous(breaks = c(100, 1000000, 2000000, 3000000, 4000000, 5000000), labels = c("100", "1M", "2M", "\n3M", "\n\n4M", "\n\n\n5M"), trans = 'log') +
  scale_y_continuous(trans='log', labels = scales::number_format(accuracy = 0.00001)) +
  theme_light() + theme(text=element_text(size = 20, family = "Times"))+ jpeg(width = 1000, height = 563, filename="graphs/hundred_n_log.png", quality = 100)

# quick select worst case:
quickselect_worst_stats %>% ggplot( aes(x = size) ) + 
  geom_line(aes(y=quickselect_average, colour="quickSelect"),size=2 )+
  stat_smooth(aes(y = quickselect_average), method = "lm", formula = y ~ x + I(x^2), size = 2, se=F, color="black", linetype="dotted") +
  labs(x = "dimensione", y = "tempo (secondi)") +
  scale_color_manual(name = "Algoritmi di selezione", values = c("quickSelect" = quickselect_color)) +
  scale_x_continuous(trans = 'log') +
  scale_y_continuous(trans = 'log', labels = scales::number_format(accuracy = 0.0001)) +
  theme_light() + theme(text=element_text(size = 20, family = "Times"))+ jpeg(width = 1000, height = 563, filename="graphs/quickselect_worst_log.png", quality = 100)
```

```{r}
# increasing k static size
static_size_stats  %>% ggplot( aes(x = k) ) + 
  geom_line(aes(y=quickselect_average,colour="quickSelect"),size=2 )+
  geom_line(aes(y=minheapselect_average,colour="minheapSelect"),size=2) +
  geom_line(aes(y=medianmediansselect_average,colour="medianMediansSelect"),size=2) +
  labs(x = "k", y = "tempo (secondi)") +
  scale_color_manual(name = "Algoritmi di selezione", values = c("quickSelect" = quickselect_color, 
                                                                 "minheapSelect" = heapSelect_color,
                                                                 "medianMediansSelect" = medianMediansSelect_color)) + 
  theme_light() + theme(text=element_text(size = 20, family = "Times"))+ jpeg(width = 1000, height = 563, filename="graphs/fixed_size_with_minheap.png", quality = 100)

static_size_stats  %>% ggplot( aes(x = k) ) + 
  geom_smooth(aes(y=quickselect_average,colour="quickSelect"),size=2 )+
  geom_smooth(aes(y=minheapselect_average,colour="minheapSelect"),size=2) +
  geom_smooth(aes(y=medianmediansselect_average,colour="medianMediansSelect"),size=2) +
  labs(x = "k", y = "tempo (secondi)") +
  scale_color_manual(name = "Algoritmi di selezione", values = c("quickSelect" = quickselect_color, 
                                                                 "minheapSelect" = heapSelect_color,
                                                                 "medianMediansSelect" = medianMediansSelect_color)) +
  theme_light() +theme(text=element_text(size = 20, family = "Times"))+ jpeg(width = 1000, height = 563, filename="graphs/fixed_size_with_minheap_smooth.png", quality = 100)
```

```{r correlation}
# correlazione lineare tra parametro k e tempi medi di esecuzione:
static_size_stats %>%
  summarise(corr_k_minheapselect = cor(k, minheapselect_average, method = "pearson"),
            corr_k_quickselect = cor(k, quickselect_average, method = "pearson"),
            corr_k_medianmediansselect = cor(k, medianmediansselect_average, method = "pearson"))

plot(static_size_stats$k, static_size_stats$medianmediansselect_average)
plot(static_size_stats$k, static_size_stats$minheapselect_average)
plot(static_size_stats$k, static_size_stats$quickselect_average)
```

```{r maxHeapSelect}
maxheapselect_color = "#26c6da"
# min-heap vs max-heap:
static_size_stats  %>% ggplot( aes(x = k) ) + 
  geom_line(aes(y=minheapselect_average,colour="minheapSelect"),size=2) +
  geom_line(aes(y=maxheapselect_average,colour="maxheapSelect"),size=2) +
  labs(x = "k", y = "tempo (secondi)") +
  scale_color_manual(name = "Algoritmi di selezione", values = c("minheapSelect" = heapSelect_color, 
                                                                 "maxheapSelect" = maxheapselect_color)) +
  theme_light() + theme(text=element_text(size = 20, family = "Times"))+ jpeg(width = 1000, height = 563, filename="graphs/fixed_size_with_maxheap.png", quality = 100)

static_size_stats  %>% ggplot( aes(x = k) ) + 
  geom_smooth(aes(y=minheapselect_average,colour="minheapSelect"),size=2) +
  geom_smooth(aes(y=maxheapselect_average,colour="maxheapSelect"),size=2) +
  labs(x = "k", y = "tempo (secondi)") +
  scale_color_manual(name = "Algoritmi di selezione", values = c("minheapSelect" = heapSelect_color, 
                                                                 "maxheapSelect" = maxheapselect_color)) +
  theme_light() + theme(text=element_text(size = 20, family = "Times"))+ jpeg(width = 1000, height = 563, filename="graphs/fixed_size_with_maxheap_smooth.png", quality = 100)
```


